definitions:
  models.CreateUserRequest:
    properties:
      first_name:
        example: John
        type: string
      last_name:
        example: Doe
        type: string
      login:
        example: johndoe
        type: string
    type: object
  models.UpdateUserRequest:
    properties:
      first_name:
        example: John
        type: string
      last_name:
        example: Doe
        type: string
      login:
        example: johndoe
        type: string
    type: object
  models.User:
    properties:
      created_at:
        description: Дата создания
        type: string
      deleted_at:
        description: Дата удаления (если есть)
        type: string
      first_name:
        description: Имя пользователя
        type: string
      id:
        description: ID пользователя
        type: integer
      last_name:
        description: Фамилия пользователя
        type: string
      login:
        description: Логин пользователя
        type: string
      updated_at:
        description: Дата обновления
        type: string
    type: object
  response.APIResponse:
    properties:
      message:
        example: ok
        type: string
      result: {}
      status:
        example: true
        type: boolean
    type: object
  response.ErrorResponse:
    properties:
      message:
        example: something went wrong
        type: string
      status:
        example: false
        type: boolean
    type: object
info:
  contact: {}
paths:
  /status:
    get:
      description: Проверяет статус API
      responses: {}
      tags:
      - check status
  /v1/users:
    get:
      description: Получает список всех пользователей
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.APIResponse'
            - properties:
                result:
                  items:
                    $ref: '#/definitions/models.User'
                  type: array
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Получить пользователей
      tags:
      - users
    post:
      consumes:
      - application/json
      description: Создает нового пользователя
      parameters:
      - description: Данные пользователя
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.CreateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.APIResponse'
            - properties:
                result:
                  $ref: '#/definitions/models.User'
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Создать пользователя
      tags:
      - users
  /v1/users/soft-delete/{id}:
    delete:
      consumes:
      - application/json
      description: Помечает пользователя как удаленого
      parameters:
      - description: ID пользователя
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Удалить пользователя
      tags:
      - users
  /v1/users/update/{id}:
    put:
      consumes:
      - application/json
      description: Обновляет пользователя
      parameters:
      - description: ID пользователя
        in: path
        name: id
        required: true
        type: integer
      - description: Данные пользователя
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.UpdateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.APIResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Обновить пользователя
      tags:
      - users
swagger: "2.0"
